preprocess:
  news_file: 'news_clean.tsv'   # 'news_clean.tsv' & 'news_bpe_{num_operation}.tsv'
  data_set: 'large'   # 'large' & 'small' & 'demo'
  use_abstract: 1
  use_body: 1
  news_max_len: 1024
  word_min_freq: 100
  vocab_path: '../../data/nrms.vocab'
  hist_max_len: 64
  neg_pos_ratio: 3
  is_demo: 0

model:
  model_name: 'NRMS'
  load_checkpoint_path: ''
  vocab_size: 0   # generate
  embed_size: 256
  hidden_size: 256
  attention_head_num: 8
  attention_size: 256
  dropout: 0.5

train:
  batch_size: 128
  optimizer: 'Adam'   # Adam & SGD
  lr: 0.0003
  momentum: 0.0
  lr_decay: 1
  warmup_steps: 10000
  train_steps: 20000
  steps_per_check: 100
  steps_per_checkpoint: 5000